 CREATE TABLE MEMBER (
        NO VARCHAR2(6) PRIMARY KEY,
        NAME VARCHAR2(32),
        AGE NUMBER,
        BIRTHDAY VARCHAR2(10),
        REGDATE DATE );
    INSERT INTO MEMBER VALUES ('851106', '이정숙', 37, '1985-11-06', SYSDATE);
    COMMIT